console.log(newTrain.name);
      console.log(newTrain.place);
      console.log(newTrain.firtrain);
      console.log(newTrain.fre);
console.log(childSnapshot.val());
console.log(trainName);
 console.log(destination);
 console.log(firstTrain);
 console.log(frequency);
 console.log(theTimeConverted);
 console.log("Current Time: " + curTime);